name: python

on:
  push:
    branches:
      - main
      - dev
      - feat-15-3Ds
  pull_request:
    branches:
      - main
      - dev

jobs:
  YunMeng_Test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt     

      - name: Run unittest tests
        run: |
          pip install pytest pytest-cov
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Upload coverage to Codecov
        if: ${{ matrix.os == 'ubuntu-22.04'}}
        uses: codecov/codecov-action@v5
        with:
          files: ./codecov.yml
          token: ${{ secrets.CODECOV_TOKEN }}      

      - name: mkdocs
        if: ${{ matrix.os == 'ubuntu-22.04'}}
        run: |
          cd ${{ github.workspace }}
          pip install mkdocs
          pip install mkdocstrings[python]
          pip install mkdocs-material             
        shell: bash  
      
      - name: deploy docs
        if: ${{ matrix.os == 'ubuntu-22.04'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
  
      - name: Build package
        run: |
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
    
      # - name: Upload to PyPI
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: twine upload dist/*          