name: python

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  YunMeng_Test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt     

      - name: Run unittest tests
        run: |
          pip install pytest pytest-cov
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Upload coverage to Codecov
        if: ${{ matrix.os == 'ubuntu-22.04' && github.ref == 'refs/heads/main' }}
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}  

      - name: mkdocs
        if: ${{ matrix.os == 'ubuntu-22.04' && github.ref == 'refs/heads/main' }}
        run: |
          cd ${{ github.workspace }}
          pip install mkdocs
          pip install mkdocstrings[python]
          pip install mkdocs-material
          mkdocs serve --no-livereload
          mkdocs gh-deploy --clean
        shell: bash      
